import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "@/components/shared/Sidebar";
import { Header } from "@/components/shared/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-black text-white">
          {/* Sidebar for larger screens */}
          <Sidebar />
          <div className="flex-1 flex flex-col">
            {/* Main content */}
            {/* Header */}
            <Header />
            {/* Mobile sidebar */}
            {/* {isSidebarOpen && (
              <MobileSidebar />
            )} */}

            <main className="flex-grow flex flex-col px-4">
              {children}
            </main>
            {/* Footer */}
            <footer className="p-4 flex flex-wrap justify-center gap-4 text-xs md:text-sm text-gray-400">
              <a href="#" className="hover:text-white">Oscar Corcho</a>
              <a href="#" className="hover:text-white">Monokera</a>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
