import type { Metadata } from "next";
import "./styles/globals.css";
import { Sidebar } from "@/components/shared/Sidebar";
import { Header } from "@/components/shared/Header";
import Providers from "@/providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="root-layout__body antialiased">
        <div className="root-layout__container">
          <Sidebar />
          <div className="root-layout__content">
            <Header />
            <main className="root-layout__main">
              <Providers>{children}</Providers>
            </main>
            <footer className="root-layout__footer">
              <a href="https://linkedin.com/in/oscar-corcho" className="root-layout__footer-link root-layout__footer-link--highlight">
                Oscar Corcho - Made with Love
              </a>
              <a href="#" className="root-layout__footer-link">
                For Monokera
              </a>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
